### ISSUE TITLE
Miss a directory

### ISSUE THREAD

**Issue by LeeRoc-China** [FeipengMa6/VSC22-Submission#7]
when i run `train/train_v68/train_v68.sh` , it told me follow:
```
...
Traceback (most recent call last):
  File "/sda/home/lipeng/Program/vsc/train/train_v68/descriptor_train.py", line 291, in <module>
    for _b, batch in enumerate(train_loader):
  File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
lmdb.Error: Caught Error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/sda/home/lipeng/Program/vsc/train/train_v68/vsc/baseline/model_factory/datasets/videolmdb_dataset.py", line 150, in __getitem__
    res = self._sample_pair(index)
  File "/sda/home/lipeng/Program/vsc/train/train_v68/vsc/baseline/model_factory/datasets/videolmdb_dataset.py", line 290, in _sample_pair
    img_a = self.transform_q(img_a)
  File "/sda/home/lipeng/Program/vsc/train/train_v68/vsc/baseline/model_factory/datasets/videolmdb_dataset.py", line 214, in transform_q
    img = Image.fromarray(sample_pipeline(image=np.array(img))["image"])
  File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/albumentations/core/composition.py", line 205, in __call__
    data = t(**data)
  File "/sda/home/lipeng/Program/vsc/train/train_v68/vsc/baseline/model_factory/transforms/argument.py", line 307, in __call__
    return super().__call__(*args, force_apply=False, **data)
  File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/albumentations/core/composition.py", line 205, in __call__
    data = t(**data)
  File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/albumentations/core/transforms_interface.py", line 118, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/albumentations/core/transforms_interface.py", line 131, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/sda/home/lipeng/Program/vsc/train/train_v68/vsc/baseline/model_factory/transforms/argument.py", line 123, in apply
    return np.array(self._transform(image))
  File "/sda/home/lipeng/Program/vsc/train/train_v68/vsc/baseline/model_factory/transforms/argument.py", line 274, in _transform
    self._open_lmdb()
  File "/sda/home/lipeng/Program/vsc/train/train_v68/vsc/baseline/model_factory/transforms/argument.py", line 258, in _open_lmdb
    self.lmdb_env = lmdb.open(
lmdb.Error: : No such file or directory
```
But i didn't modify the config file. How to fix this error?

In addition, Your Readme mentioned `data/lmdb/dics` , and the config file also mentioned this, i didn't find this, and how to generate this directory?
```python
data = dict(
    train=dict(
        type="LabelVideoLmdbDataSet", # VideoLmdbDataSet LabelVideoLmdbDataSet
        vids_path=[f"{root_dir}/data/meta/train/train_ref_vids.txt", f"{root_dir}/data/meta/train/train_query_id.csv"],
        meta_path=f"{root_dir}data/lmdb/vsc/meta.npz",
        lmdb_path=f"{root_dir}data/lmdb/vsc",
        lmdb_size=1e12,
        preprocess=preprocess,
        width=img_width,
        ann_path=f"{root_dir}/data/meta/train/train_matching_ground_truth.csv",
    ),
    train1=dict(
        type="VideoLmdbDataSet", # VideoLmdbDataSet LabelVideoLmdbDataSet
        vids_path=[],
        meta_path=f"{root_dir}/data/lmdb/dics/meta.npz",
        lmdb_path=f"{root_dir}/data/lmdb/dics",
        lmdb_size=1e12,
        preprocess=preprocess,
        width=img_width,
    ),
)
```

**Comment by QuinVIVER** [comment]
How do  you pass the training of train_vid_score.sh? my training always failed with a RuntimeError    : replicas[0][0] in this process with sizes [1024] appears not to match sizes of the same param in process 0, under cuda11.3+pytorch 1.11 according to the setup.sh.

**Comment by wlpku123** [comment]
> 当我运行程序时`train/train_v68/train_v68.sh`，它提示我执行以下操作：
> 
> ```
> ...
> Traceback (most recent call last):
>   File "/sda/home/lipeng/Program/vsc/train/train_v68/descriptor_train.py", line 291, in <module>
>     for _b, batch in enumerate(train_loader):
>   File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
>     data = self._next_data()
>   File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
>     return self._process_data(data)
>   File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
>     data.reraise()
>   File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/torch/_utils.py", line 457, in reraise
>     raise exception
> lmdb.Error: Caught Error in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/sda/home/lipeng/Program/vsc/train/train_v68/vsc/baseline/model_factory/datasets/videolmdb_dataset.py", line 150, in __getitem__
>     res = self._sample_pair(index)
>   File "/sda/home/lipeng/Program/vsc/train/train_v68/vsc/baseline/model_factory/datasets/videolmdb_dataset.py", line 290, in _sample_pair
>     img_a = self.transform_q(img_a)
>   File "/sda/home/lipeng/Program/vsc/train/train_v68/vsc/baseline/model_factory/datasets/videolmdb_dataset.py", line 214, in transform_q
>     img = Image.fromarray(sample_pipeline(image=np.array(img))["image"])
>   File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/albumentations/core/composition.py", line 205, in __call__
>     data = t(**data)
>   File "/sda/home/lipeng/Program/vsc/train/train_v68/vsc/baseline/model_factory/transforms/argument.py", line 307, in __call__
>     return super().__call__(*args, force_apply=False, **data)
>   File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/albumentations/core/composition.py", line 205, in __call__
>     data = t(**data)
>   File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/albumentations/core/transforms_interface.py", line 118, in __call__
>     return self.apply_with_params(params, **kwargs)
>   File "/sda/home/lipeng/anaconda3/envs/vsc/lib/python3.9/site-packages/albumentations/core/transforms_interface.py", line 131, in apply_with_params
>     res[key] = target_function(arg, **dict(params, **target_dependencies))
>   File "/sda/home/lipeng/Program/vsc/train/train_v68/vsc/baseline/model_factory/transforms/argument.py", line 123, in apply
>     return np.array(self._transform(image))
>   File "/sda/home/lipeng/Program/vsc/train/train_v68/vsc/baseline/model_factory/transforms/argument.py", line 274, in _transform
>     self._open_lmdb()
>   File "/sda/home/lipeng/Program/vsc/train/train_v68/vsc/baseline/model_factory/transforms/argument.py", line 258, in _open_lmdb
>     self.lmdb_env = lmdb.open(
> lmdb.Error: : No such file or directory
> ```
> 
> 但我并没有修改配置文件。如何解决这个错误？
> 
> 此外，您的自述文件`data/lmdb/dics`和配置文件中都提到了这一点，但我没有找到，请问如何生成这个目录？
> 
> data = dict(
>     train=dict(
>         type="LabelVideoLmdbDataSet", # VideoLmdbDataSet LabelVideoLmdbDataSet
>         vids_path=[f"{root_dir}/data/meta/train/train_ref_vids.txt", f"{root_dir}/data/meta/train/train_query_id.csv"],
>         meta_path=f"{root_dir}data/lmdb/vsc/meta.npz",
>         lmdb_path=f"{root_dir}data/lmdb/vsc",
>         lmdb_size=1e12,
>         preprocess=preprocess,
>         width=img_width,
>         ann_path=f"{root_dir}/data/meta/train/train_matching_ground_truth.csv",
>     ),
>     train1=dict(
>         type="VideoLmdbDataSet", # VideoLmdbDataSet LabelVideoLmdbDataSet
>         vids_path=[],
>         meta_path=f"{root_dir}/data/lmdb/dics/meta.npz",
>         lmdb_path=f"{root_dir}/data/lmdb/dics",
>         lmdb_size=1e12,
>         preprocess=preprocess,
>         width=img_width,
>     ),
> )

单步调试了很久,他的代码里面有很多虚拟路径可能会和你运行的路径不同导致报错,可以改改着真实路径就不会报错
